outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Webhook
      uses: thiiagocosta/thiagocosta@main
      with:
        url: "https://webhooks.hostinger.com/deploy/5ca270934cd57233848b3ac5a77cb63f"
        json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'